---
title: "MARCO NORMATIVO"
date: "Atualizado al `r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
En esta sección se presenta por país las diferentes leyes y/o normativas **vigentes** que componen el marco regulatorio referente al tema de Prevención de Lavado de Activos, Financiamiento al Terrorismo y Proliferación de Armas de Destrucción Masiva (LD/FT/PADM) 

# COSTA RICA

## Ordenamiento Jurídico Internacional

- [Convención de las Naciones Unidas contra el Tráfico Ilícito de Estupefacientes y Sustancias Sicotrópicas](http://www.uif.gob.sv/wp-content/uploads/convenciones/01-Convencion-de-las-Naciones-Unidas-contra-el-Trafico-Ilicito-Viena-1988.pdf)

- [Convención de las Naciones Unidas contra la Corrupción](http://www.uif.gob.sv/wp-content/uploads/convenciones/03-Convencion-de-las-Naciones-Unidas-contra-la-Corrupcion.pdf)

- [Convención de las Naciones Unidas Contra la Delincuencia Organizada Transnacional (Convenio de Palermo, 2000)](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=50810&nValor3=54705&strTipM=TC)

## Ordenamiento Jurídico Secundario

- [LEY 7786-Ley sobre estupefacientes, sustancias psicotrópicas, drogas de uso No Autorizado, actividades Conexas, legitimación de capitales y financiamiento al terrorismo](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=29254)

- [LEY 8719-Reforma integral Ley sobre estupefacientes, sustancias psicotrópicas, drogas de uso no autorizado, actividades conexas, legitimación de capitales y financiamiento al terrorismo](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=48392&nValor3=93996&strTipM=TC)

- [LEY 8719-Ley de Fortalecimiento de la legislación contra el terrorismo](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/normas/nrm_texto_completo.aspx?param2=2&nValor1=1&nValor2=65070&nValor3=75876&nValor4=NO&strTipM=TC)

- [LEY 8754-Ley Contra la Delincuencia Organizada](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=65903&nValor3=87003&strTipM=TC)

- [LEY 9074-Modificación de la ley N° 8204, Ley sobre Estupefacientes, Sustancias Psicotrópicas, Drogas de uso no autorizado, Actividades Conexas, Legitimación de Capitales y Financiamiento al Terrorismo](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=74240&nValor3=91611&strTipM=TC)

- [LEY 9161-Reforma Ley N° 8204 "Reforma integral Ley sobre estupefacientes, sustancias psicotrópicas, drogas de uso no autorizado, actividades conexas, legitimación capitales y financiamiento terrorismo", para introducir la proporcionalidad y especificidad de género](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=75699&nValor3=93995&strTipM=TC)

- [LEY 9387-Reforma Ley sobre estupefacientes, sustancias psicotrópicas, drogas de uso No Autorizado, actividades Conexas, legitimación de](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=82027&nValor3=104832&strTipM=TC)

- [LEY 9449-Reforma Ley sobre estupefacientes, sustancias psicotrópicas, drogas de uso No Autorizado, actividades Conexas, legitimación de capitales y financiamiento al terrorismo](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=83999&nValor3=108173&strTipM=TC)

- [Reglamento para la prevención del riesgo de legitimación de capitales, financiamiento al terrorismo y financiamiento de la proliferación](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=90071&nValor3=118480&strTipM=TC)

- [Reglamento para la inscripción y desinscripción ante la SUGEF de los sujetos obligados que realizan alguna o algunas de las actividades en los artículos 15 y 15 bis de ley estupefacientes sustancias psicotrópicas, drogas de uso no autorizado (SUGEF 11-18)](http://www.pgrweb.go.cr/scij/Busqueda/Normativa/Normas/nrm_texto_completo.aspx?param1=NRTC&nValor1=1&nValor2=87558&nValor3=118971&strTipM=TC)

- [Reglamento para la prevención del riesgo de legitimación de capitales, financiamiento al terrorismo y financiamiento de la proliferación](https://www.sugef.fi.cr/ver/normativa/normativa_vigente/Sugef%2012-21%20%20(v05%2018%20agosto%202021).pdf#.YUDMTJ1KiyJ)

- [ACUERDO SUGEF 12-10- NORMATIVA PARA EL CUMPLIMIENTO DE LA LEY Nº 8204](https://www.sugef.fi.cr/ver/normativa/normativa_vigente/SUGEF%2012-10%20(v21%2016%20de%20setiembre%20de%202020).pdf#.YUDMMZ1KiyJ)

- [ACUERDO SUGEF 13-19- REGLAMENTO PARA LA PREVENCIÓN DEL RIESGO DE LEGITIMACIÓN DE CAPITALES](https://www.sugef.fi.cr/ver/normativa/normativa_vigente/SUGEF%2013-19%20(v5%2025%20noviembre%202020).pdf#.YUDMGp1KiyJ)

- [ACUERDO SUGEF 35-21-REGLAMENTO DEL CENTRO DE INFORMACIÓN CONOZCA A SU CLIENTE](https://www.sugef.fi.cr/ver/normativa/normativa_vigente/Sugef%2035-21%20%20(v04%2016%20abril%202021).pdf#.YUDMBZ1KiyJ)


## Buenas Prácticas

- [LAS RECOMENDACIONES DEL GAFI- ESTÁNDARES INTERNACIONALES SOBRE LA LUCHA CONTRA EL LAVADO DE ACTIVOS, EL FINANCIAMIENTO DEL TERRORISMO Y LA PROLIFERACIÓN DE ARMAS DE DESTRUCCIÓN MASIVA (Las 40 Recomendaciones del GAFI/FATF)](https://www.gafilat.org/index.php/es/biblioteca-virtual/gafilat/documentos-de-interes-17/publicaciones-web/4013-recomendaciones-metodologia-actdic20-1/file)

- [PRINCIPIOS DE WOLFSBERG PARA LA PREVENCION DEL BLANQUEO DE DINERO EN BANCA DE CORRESPONSALES](https://www.wolfsberg-principles.com/sites/default/files/wb/pdfs/translations/spanish/105.%20correspondent-spanish.pdf)

- [Ley Patriot de los EE.UU](https://www.congress.gov/107/plaws/publ56/PLAW-107publ56.pdf)

- [COMITE DE BASILEA SOBRE SUPERVISIÓN BANCARIA](https://www.bis.org/bcbs/basel3_es.htm)